name: "Build"

on:
  push:
    branches:
      - "main"
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"
    permissions:
      packages: "write"
    env:
      # GitHub Actions expressions conditionals are ternary expressions that
      # look a lot like bash. In Python, this would read as:
      #
      #     github.ref_name if github.ref_type == 'tag' else 'latest'
      #
      # https://docs.github.com/en/actions/learn-github-actions/expressions
      IMAGE_TAG: "${{ github.ref_type == 'tag' && github.ref_name || 'latest' }}"

    steps:
      - uses: "actions/checkout@v3"

      # - name: "Check version"
      #   run: "source .env && test ${{ github.ref_name }} = ${VERSION}" 
      #     # TODO: Trigger on push to main; if github.ref_name is `main`, then build latest.
      #     # Else, build tagged version and check that $VERSION matches the tag.

      - name: "Build"
        run: "docker compose build"

      - name: "GHCR login"
        uses: "docker/login-action@v2"
        with:
          registry: "ghcr.io"
          username: "${{ github.repository_owner }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - name: "Push to image registry"
        run: "docker compose push"
