name: "Build"

on:
  push:
    branches:
      - "main"
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"

      # - name: "Check version"
      #   run: "source .env && test ${{ github.ref_name }} = ${VERSION}" 
      #     # TODO: Trigger on push to main; if github.ref_name is `main`, then build latest.
      #     # Else, build tagged version and check that $VERSION matches the tag.

      - name: "Build"
        run: "docker compose build"
